package com.example.tools;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.TreeSet;

/**
 * Created by bing.zhao on 2016/12/5.
 */

public class XmlParser {


    public static void main(String[] args){
        TreeSet<String> set = new TreeSet<>();
        String strReader = "F:\\copy" + File.separator + "strings.xml";
        String strWriter= "F:\\copy" + File.separator + "string.xml";
        File fileR = new File(strReader);
        File fileW = new File(strWriter);
        try {
            BufferedReader br = new BufferedReader(new FileReader(fileR));
            BufferedWriter bw = new BufferedWriter(new FileWriter(fileW));
            String temp = null;
            while((temp = br.readLine()) != null){
                String key = getKey(temp);
                if(key.equals("null")){

                }else{
//                    System.out.println(key);
                    set.add(key);
//                    bw.write(key+"\n");
                }

            }


            for(String str:set){
                bw.write(str+"\n");
            }

            bw.write("不存在的id\n");
            System.out.println("不存在的id:");
            for(String str : set){
                boolean flag = false;
                for(int i = 0 ;i<exitArray.length; i++){
                    if(exitArray[i].equals(str)){
                        flag = true;
                        break;
                    }
                }
                if(!flag){
                    System.out.println(str);
                    bw.write(str+"\n");
                }
            }

            bw.write("多余的id\n");
            System.out.println("多余的id:");

            for(String str : exitArray){
                boolean flag = false;
                for(String setStr : set){
                    if(setStr.equals(str)){
                        flag = true;
                        break;
                    }
                }
                if(!flag){
                    System.out.println(str);
                    bw.write(str+"\n");
                }
            }

            br.close();
            bw.flush();
            bw.close();

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public static String getKey(String str){
//        int startIndex = str.indexOf('\"');
//        if(startIndex == -1){
//            return "null";
//        }
//        int endIndex = str.lastIndexOf('\"');
////        System.out.println("sIndex = " + startIndex + ",eIndex = " + endIndex);
//        return str.substring(startIndex+1,endIndex);
        String[] array = str.split("\"");
        if(array != null && array.length >2 ){
            return array[1];
        }else{
            return "null";
        }


    }

    public static String exitArray[]={
            "gender",
            "male",
            "female",
            "height",
            "weight",
            "str_inch",
            "steps",
            "string_add_more",
            "length_units_ft",
            "today",
            "str_set_bluetooth_open",
            "str_bluetooth_connecting",
            "setting_my_clock_repeat",
            "device_bind_available_devices",
            "str_snapshot_waitting",
            "setting_notifications_Listener_dialog_title",
            "setting_notifications_missed_call",
            "setting_notifications_Listener_dialog_content",
            "setting_notifications_Listener_dialog_nexttime",
            "setting_notifications_Listener_dialog_ok",
            "dfu_upgrade_firmware",
            "dfu_upgrade_start_download_firmware",
            "version_check_network_err",
            "every_day",
            "string_help_option_user_manual",
            "string_my_achievement_menu",
            "string_set_goals_title",
            "login_state_logout",
            "str_confirm_logout_notice",
            "str_login_later",
            "str_login_request_failed_error",
            "str_register_password_error",
            "Username_wrong",
            "str_network_no_connection",
            "str_repeat_password_error",
            "str_get_image_file_fail",
            "str_change_password_done",
            "never",
            "string_device_bluetooth_tips",
            "string_ble_not_support",
            "ble_rom_version_older",
            "str_remove_alarm_title",
            "smartband_pair_connect_guide_tip1",
            "apk_crash_tips",
            "date_am",
            "date_pm",
            "bt_scan_gps_prompt",
            "smartband_setting_wallpaper_take_photo",
            "smartband_setting_wallpaper_crop_image",
            "smartband_setting_wallpaper_crop_pinch",
            "smartband_setting_wallpaper_cancel",
            "smartband_setting_wallpaper_crop",
            "smartband_setting_wallpaper_cannot_load",
            "smartband_setting_wallpaper_ok",
            "select_image",
            "smartband_my_profile_weight",
            "string_could_not_download_update_firmware",
            "ahieve_workout_45min_name",
            "ahieve_workout_90min_name",
            "ahieve_day1_name",
            "ahieve_day7_name",
            "ahieve_day90_name",
            "ahieve_day365_name",
            "ahieve_day500_name",
            "ahieve_social_share_30_times_name",
            "ahieve_fall_in_love_detail",
            "string_achievement_share",
            "Sunday_short",
            "Monday_short",
            "Tuesday_short",
            "Wednesday_short",
            "Thursday_short",
            "Friday_short",
            "Saturday_short",
            "string_smart_wake_up",
            "string_smart_wake_up_detail",
            "day",
            "hour",
            "minute",
            "hour_picker_description",
            "minute_picker_description",
            "select_hours",
            "select_minutes",
            "day_picker_description",
            "year_picker_description",
            "select_day",
            "select_year",
            "clear_label",
            "string_firmware_download_popup_content",
            "setting_notifications_sms",
            "password",
            "ep_friend_request_cancel",
            "notification_selected_max_count",
            "connect_device",
            "save_pic_wait_content",
            "permission_cancle",
            "permission_ok",
            "permission_message",
            "vcode_wrong",
            "account_used",
            "username_password_not_match",
            "email_used",
            "send_input_code",
            "verification_code",
            "invalid_code",
            "help",
            "mother",
            "ok",
            "cancel",
            "exception",
            "send_success",
            "Modify_chnage",
            "Modify_failed",
            "new_password",
            "sent_failed",
            "start_to_use",
            "input_your_new_password",
            "exception_message_generic",
            "exception_message_no_connection",
            "exception_message_user_not_found",
            "login_status_invalid",
            "me",
            "Delete_Valid_failed",
            "track_your_activities",
            "receive_information",
            "playing_music",
            "username_does_not_exist",
            "saving_please_wait",
            "avg_step",
            "total_km",
            "streaks",
            "set_goal",
            "achievement",
            "profile",
            "name",
            "default_name",
            "email",
            "default_email",
            "change_password",
            "old_password_wrong",
            "default_password",
            "default_height",
            "default_weight",
            "default_birthday",
            "birth_date",
            "orientation",
            "left_wrist",
            "right_wrist",
            "Female",
            "old_password",
            "re_enter_new_password",
            "having_fun_step_by_step",
            "good_sleep_night_by_night",
            "skip_for_now",
            "login",
            "sign_up",
            "your_email",
            "re_enter_password",
            "skip",
            "protect_your_account",
            "resend",
            "done",
            "password_recovery",
            "send_verification_code_to",
            "set_profile",
            "nick_name",
            "user_info_warming",
            "moveband_orientation",
            "pair_moveband",
            "add_moveband",
            "pairing_moveband_with_your_phone",
            "binded",
            "unbinded",
            "turn_on_your_phone",
            "turn_on_bluetooth",
            "this_band_is_already_binded",
            "please_login_to_connect",
            "bind_fail",
            "kg",
            "lbs",
            "ft_in",
            "default_achievements",
            "default_achievement",
            "alarm",
            "alarms",
            "alarms_on",
            "no_alarm_set",
            "notifications",
            "allowed",
            "gesture",
            "gesture_with_your_palm",
            "turn_over_wrist",
            "camera_on",
            "music_on",
            "camera",
            "camera_with_your_palm",
            "music",
            "music_with_your_palm",
            "paired",
            "added",
            "not_added",
            "charging",
            "battery",
            "off",
            "pair_new_device",
            "days_since_last_charge",
            "find_my_wristband",
            "wristband_will_flash_and_vibrate",
            "about_device",
            "unpair_this_will_delete_all_data",
            "unpair_are_you_sure",
            "reset_this_will_delete_all_data",
            "reset_are_you_sure",
            "delete_moveband",
            "erase_all_data_and_reset",
            "delete",
            "firmware",
            "model",
            "serial_number",
            "bluetooth",
            "moveband_settings",
            "unpaired",
            "unpaired_success",
            "delete_success",
            "delete_fail",
            "unpaired_fail",
            "paired_devices",
            "devices_added_to",
            "rename_moveband",
            "rename",
            "rename_success",
            "rename_fail",
            "save",
            "reset_moveband",
            "unpair_moveband",
            "unbind_moveband",
            "erase_all_settings",
            "delete_moveband1",
            "give_a_nice_name",
            "morgan_moveband",
            "term_of_use",
            "privacy_and_security",
            "hotlines",
            "feedback",
            "lower_steps",
            "fitness",
            "moveband",
            "sleep",
            "sleep_total",
            "sleep_bedtime",
            "sleep_wake",
            "string_km",
            "string_kcal",
            "string_minute",
            "string_hour",
            "string_day",
            "string_week",
            "string_month",
            "string_year",
            "reach_your_daily",
            "daily_goal_prompt_message",
            "change_password_finished",
            "user_name_is_exit",
            "register_failed",
            "update_to",
            "check_new_version",
            "input_name",
            "update_finished",
            "connected_interrupted",
            "update_failed",
            "check_new_version_please_wait",
            "upgrade_to",
            "visitor",
            "can_continue_to",
            "please_wait",
            "action_settings",
            "setted_daily_goal_failed",
            "smartband_my_profile_metirc_unit",
            "profile_down",
            "forgot_password",
            "new_comer",
            "First_workout_over_15_minutes",
            "First_workout_over_45_minutes",
            "First_workout_over_90_minutes",
            "seven_workout_week",
            "perfect_month",
            "new_goal",
            "new_record",
            "double_move",
            "triple_move",
            "quadruple_move",
            "longest_streak",
            "string_days",
            "most_recent",
            "new_comer_no_get",
            "new_comer_discription",
            "new_comer_no_get_share_discription",
            "new_comer_share_discription",
            "no_get_before_first_over_15",
            "no_get_share_first_over_15",
            "first_over_15_before_share",
            "first_over_15_after_share",
            "no_get_first_over_45_before_share",
            "no_get_first_over_45_after_share",
            "first_over_45_before_share",
            "first_over_45_after_share",
            "no_get_first_over_90_before_share",
            "no_get_first_over_90_after_share",
            "first_over_90_before_share",
            "first_over_90_after_share",
            "get_badge_time",
            "get_badge_times",
            "no_get_share_before_perfect_day",
            "no_get_share_after_perfect_day",
            "perfect_day_before_share",
            "perfect_day_after_share",
            "no_get_seven_workout_before_share",
            "no_get_seven_workout_after_share",
            "seven_workout_before_share",
            "seven_workout_after_share",
            "no_get_perfect_week_before_share",
            "no_get_perfect_week_after_share",
            "perfect_week_before_share",
            "perfect_week_after_share",
            "no_get_perfect_month_before_share",
            "perfect_month_before_share",
            "perfect_month_after_share",
            "no_get_new_goal_before_share",
            "no_get_new_goal_after_share",
            "new_goal_before_share",
            "new_goal_after_share",
            "most_rescent_max_step",
            "no_get_new_record_before_share",
            "no_get_new_record_after_share",
            "new_record_before_share",
            "new_record_after_share",
            "no_get_double_before_share",
            "no_get_double_after_share",
            "double_before_share",
            "double_after_share",
            "no_get_triple_before_share",
            "no_get_triple_after_share",
            "triple_before_share",
            "triple_after_share",
            "no_get_quadruple_before_share",
            "no_get_quadruple_after_share",
            "quadruple_before_share",
            "quadruple_after_share",
            "no_get_social_idol_before_share",
            "no_get_social_idol_after_share",
            "social_idol_before_share",
            "social_idol_after_share",
            "longest_counts",
            "no_get_logest_streak_before_share",
            "no_get_logest_streak_after_share",
            "logest_streak_before_share",
            "logest_streak_after_share",
            "no_get_top_athlete_before_share",
            "no_get_top_athlete_after_share",
            "top_athlete_before_share",
            "top_athlete_after_share",
            "no_get_terminator_before_share",
            "no_get_tterminator_after_share",
            "terminator_before_share",
            "terminator_after_share",
            "no_get_perpetual_mobile_before_share",
            "no_get_perpetual_mobile_after_share",
            "perpetual_mobile_before_share",
            "perpetual_mobile_after_share",
            "update",
            "new_firmware_downloaded",
            "device_mode",
            "device_lastest_version",
            "please_login",
            "connecting_moveband",
            "connected_moveband",
            "can_not_connect",
            "activate_moveband",
            "string_distance",
            "click_again_exit_MoveBand",
            "security_privacy_policy",
            "gallery",
            "choose_picture",
            "take_a_photo",
            "must_select_agree",
            "str_share_failed",
            "get_device_version_failed",
            "login_wait_content",
            "if_missed",
            "moveband_out_of_reach",
            "make_sure_your_moveband_is_nearby",
            "new_password_8_16_letters_or_numbers",
            "password_8_16_letters_or_numbers",
            "make_sure_your_battery_level",
            "active_device_failed",
            "lable",
            "str_photo_change",
            "incoming_call",
            "disconnect_the_bluetooth",
            "force_logout",
            "sleep_deep",
            "the_name_cannot_be_empty",
            "current_number",
            "contact_us",
            "how_to_use_moveband",
            "terms_of_use",
            "more",
            "official_website",
            "how_to_use_gesture_tittle1",
            "battery_status",
            "double_tap_check",
            "percent_33",
            "percent_66",
            "percent_100",
            "confirm_password",
            "allow_all",
            "disallow_all",
            "connecting",
            "daily_avg",
            "about_moveband",
            "to_start_settings_add_MoveBand_first",
            "to_start_settings_login_and__add_MoveBand_first",
            "not_now",
            "add",
            "Login",
            "disconnect",
            "connected",
            "moveband_app",
            "firmware_update",
            "MAC_address",
            "str_on",
            "str_off",
            "str_my_devices",
            "str_not_connected",
            "str_connected",
            "str_scan",
            "complete",
            "ahieve_day5_name",
            "ahieve_day9_name",
            "ahieve_social_share_3_times_name",
            "ahieve_workout_9min_name",
            "days_remaining",
            "first_over_9_after_share",
            "first_over_9_before_share",
            "First_workout_over_9_minutes",
            "i_have_read",
            "no_get_first_over_9_after_share",
            "no_get_first_over_9_before_share",
            "up_to_one_device",
            "str_register_username_error",
            "lastest_version_no_update",
            "new_firmware_is_update",
            "change_password_failed",
            "username_not_find",
            "str_ensure_disconnect_moveband",
            "str_disconnect_moveband",
            "login_out",
            "str_internet_error",
            "downloading",
            "downloading_failed_from_fota_server",
            "str_username_error",
            "login_failed",
            "please_input",
            "logging_please_wait",
            "verfication_code_was_send_to",
            "send_valid_code",
            "send_verification_code",
            "str_or",
            "by_continuing",
            "help_us_protect",
            "string_calorie",
            "toast_camera_permission",
            "str_setting_successful",
            "str_account",
            "drawer_open",
            "drawer_close",
            "password_is_too_short",
            "send_verification_code2",
            "user_terms_privacy_policy",
            "str_ensure_cancel_reconnect_moveband",
            "str_cancel_reconnect",
            "bluetooth_off",
            "set_the_alarm_clock_is",
            "largest_number_of_five",
    };

}
